export 'package:flutter/material.dart';
export 'package:slashhub_app/core/theme/styles_manager.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:slashhub_app/core/theme/color_manager.dart';
export 'package:slashhub_app/core/common_widgets/default_sized_box.dart';
export 'package:slashhub_app/features/get_all_movies/data/models/movies_model.dart';
export 'package:slashhub_app/core/helpers/app_images.dart';
export 'package:slashhub_app/features/get_all_movies/presentation/widgets/movie_details_info_text.dart';
export 'package:slashhub_app/features/get_all_movies/presentation/widgets/movie_image.dart';
